/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Prediction } from './prediction';


export interface Match { 
    status: Match.StatusEnum;
    scoreFirstTeam: number;
    scoreSecondTeam: number;
    predictions: Array<Prediction>;
    id: string;
    createdAt: string;
    updatedAt: string;
    version: number;
}
export namespace Match {
    export const StatusEnum = {
        Ongoing: 'ONGOING',
        Completed: 'COMPLETED',
        Inactive: 'INACTIVE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


