/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MfaEnableResponseDto { 
    /**
     * Success message after enabling MFA
     */
    message: string;
    /**
     * Recovery codes for account access if MFA device is lost
     */
    recoveryCodes: Array<string>;
}

