/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationDataAnyOf1RankingsInner } from './notificationDataAnyOf1RankingsInner';
import { NotificationDataAnyOf } from './notificationDataAnyOf';
import { NotificationDataAnyOf1 } from './notificationDataAnyOf1';


/**
 * Additional data for the notification
 */
export interface NotificationData { 
    gain?: number;
    newDiamonds?: number;
    rankings?: Array<NotificationDataAnyOf1RankingsInner>;
}

