/**
 * KickStream API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Notification {
  userId: string;
  type: Notification.TypeEnum;
  message: string;
  data: MessageData;
  read: boolean;
  id: string;
  createdAt: string;
  updatedAt: string;
  version: number;
}

interface MessageData {
  gain: number;
  newDiamonds: number;
}

export namespace Notification {
  export const TypeEnum = {
    ChangeOfPossessedGems: 'CHANGE_OF_POSSESSED_GEMS',
    DiamondUpdate: 'DIAMOND_UPDATE',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
