/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationDataAnyOf1RankingsInner } from './notificationDataAnyOf1RankingsInner';


export interface NotificationDataAnyOf1 { 
    rankings?: Array<NotificationDataAnyOf1RankingsInner>;
}

