/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationDataAnyOf1RankingsInner { 
    firstName?: string;
    lastName?: string;
    score?: number;
    imageUrl?: string;
}

