/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationData } from './notificationData';


export interface Notification { 
    data?: NotificationData | null;
    userId: string;
    type: Notification.TypeEnum;
    message: string;
    read: boolean;
    id: string;
    createdAt: string;
    updatedAt: string;
    version: number;
}
export namespace Notification {
    export const TypeEnum = {
        ChangeOfPossessedGems: 'CHANGE_OF_POSSESSED_GEMS',
        DiamondUpdate: 'DIAMOND_UPDATE',
        RankingUpdate: 'RANKING_UPDATE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


