/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface OAuthResponseDto { 
    /**
     * JWT access token
     */
    accessToken?: string;
    /**
     * JWT refresh token
     */
    refreshToken?: string;
    user: UserDto;
}

