/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResetPasswordDto { 
    /**
     * Reset password token received in email
     */
    token: string;
    /**
     * New password
     */
    password: string;
}

