/**
 * KickStream API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    /**
     * User ID
     */
    id: string;
    /**
     * User email
     */
    email: string;
    /**
     * User first name
     */
    firstName: string;
    /**
     * User last name
     */
    lastName: string;
    /**
     * User image
     */
    imgUrl?: string;
    /**
     * Whether MFA is enabled
     */
    isMFAEnabled?: boolean;
    /**
     * User diamonds
     */
    diamonds: number;
}

